"""Agent memory: write structured context documents to the run working directory.

Each call to :func:`write_memory` produces a file whose first line is a
machine-readable summary comment followed by the raw content.  The summary is
generated by querying the Claude SDK (real runs) or computed deterministically
(stub runs and SDK failures).
"""

from __future__ import annotations

import asyncio
import hashlib
import logging
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from agentic.context import RunContext

logger = logging.getLogger(__name__)

# Maximum characters of content forwarded to the SDK for summarisation.
_QUERY_CONTENT_LIMIT = 4_000

# Maximum characters shown in the excerpt portion of the fallback summary.
_EXCERPT_CHARS = 80

# Length of the hex digest appended to every fallback summary.
_DIGEST_CHARS = 8


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def write_memory(
    path: Path | str,
    content: str,
    ctx: "RunContext",
    *,
    summary: str | None = None,
) -> Path:
    """Write *content* to *path* inside the run working directory.

    Parameters
    ----------
    path:
        Destination file, either absolute or relative to ``ctx.working_dir``.
    content:
        Raw text to persist.
    ctx:
        Active run context; used to locate the working directory and to
        determine whether stub mode is active.
    summary:
        Optional caller-supplied one-line description of the content.  When
        omitted, the summary is produced by :func:`_generate_summary`.

    Returns
    -------
    Path
        Resolved path of the file that was written.
    """
    dest = _resolve_dest(path, ctx)
    dest.parent.mkdir(parents=True, exist_ok=True)

    if summary is None:
        summary = _generate_summary(content, ctx)

    dest.write_text(_format_file(summary, content), encoding="utf-8")
    logger.info("memory written to %s (summary=%r)", dest, summary)
    return dest


# ---------------------------------------------------------------------------
# Internal helpers for write_memory
# ---------------------------------------------------------------------------


def _resolve_dest(path: Path | str, ctx: "RunContext") -> Path:
    p = Path(path)
    return p if p.is_absolute() else ctx.working_dir / p


def _format_file(summary: str, content: str) -> str:
    """Return the on-disk representation: a summary header followed by content."""
    return f"<!-- summary: {summary} -->\n{content}"


# ---------------------------------------------------------------------------
# Summary generation
# ---------------------------------------------------------------------------


def _generate_summary(content: str, ctx: "RunContext") -> str:
    """Return a one-line summary of *content*.

    The summary strategy depends on run mode:

    stub mode
        The deterministic :func:`_fallback_summary` is returned immediately.
        No network calls are made.  This keeps test runs fast and hermetic.

    real mode (default)
        The Claude SDK is queried via :func:`_query_summary`.  If that query
        raises any exception -- network failure, auth error, quota exhaustion,
        or anything else -- a ``WARNING`` log is emitted and the function
        returns :func:`_fallback_summary` instead of propagating the error.
        Memory writes must not abort agent runs over a non-essential summary.

    The caller may bypass this function entirely by passing an explicit
    *summary* keyword argument to :func:`write_memory`.
    """
    if ctx.stub_mode:
        return _fallback_summary(content)

    # Real mode: prefer the SDK summary but treat any failure as non-fatal.
    # The try/except below is the only place in this module that swallows
    # exceptions, and it does so intentionally: a failed summary is never
    # worth aborting an agent run.
    try:
        return _query_summary(content)
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "memory: _query_summary raised %s: %s -- using deterministic fallback",
            type(exc).__name__,
            exc,
        )
        return _fallback_summary(content)


# ---------------------------------------------------------------------------
# SDK query (real path only)
# ---------------------------------------------------------------------------


async def _run_query(content: str) -> str:
    """Run the SDK query coroutine and return the first text response."""
    from claude_agent_sdk import (  # type: ignore[import-not-found]
        AssistantMessage,
        ClaudeAgentOptions,
        TextBlock,
        query,
    )

    prompt = (
        "In one sentence (at most 20 words), summarise what the following "
        f"document is about.\n\n{content[:_QUERY_CONTENT_LIMIT]}"
    )
    options = ClaudeAgentOptions(allowed_tools=[])
    parts: list[str] = []
    async for message in query(prompt=prompt, options=options):
        if isinstance(message, AssistantMessage):
            for block in message.content:
                if isinstance(block, TextBlock):
                    parts.append(block.text)
    return " ".join(parts).strip() or _fallback_summary(content)


def _query_summary(content: str) -> str:
    """Synchronous entry point for the SDK query."""
    return asyncio.run(_run_query(content))


# ---------------------------------------------------------------------------
# Deterministic fallback (no network, no SDK)
# ---------------------------------------------------------------------------


def _fallback_summary(content: str) -> str:
    """Produce a deterministic, network-free summary of *content*.

    The summary consists of an excerpt from the first non-blank line of the
    content plus a stable SHA-1 hex digest, so two distinct documents always
    produce distinct summary strings.
    """
    first_line = next(
        (ln.strip() for ln in content.splitlines() if ln.strip()),
        "",
    )
    excerpt = first_line[:_EXCERPT_CHARS]
    digest = hashlib.sha1(  # noqa: S324
        content.encode(), usedforsecurity=False
    ).hexdigest()[:_DIGEST_CHARS]
    return f"{excerpt} [{digest}]" if excerpt else f"[{digest}]"
